//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileNewProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string AnhBia { get; set; }
        public string AnhSl { get; set; }
        public string AnhSli { get; set; }
        public string AnhSlid { get; set; }
        public string AnhSlide { get; set; }
        public string XuatXu { get; set; }
        public string Mau { get; set; }
        public string Pin { get; set; }
        public string Camera { get; set; }
        public string ThoiGianBay { get; set; }
        public string ThoiGianSac { get; set; }
        public string TrongLuong { get; set; }
        public int MaNSX { get; set; }
        public int MaMS { get; set; }
        public int MaNhaSX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual NoiSanXuat NoiSanXuat { get; set; }
    }
}
